name: Build Go Binary
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: |
          go mod init gostreamer
          go get github.com/celestix/gotgproto@latest
          go get github.com/gotd/td@latest
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o streamer_go
      - uses: actions/upload-artifact@v4
        with:
          name: streamer_go
          path: streamer_go
